# Generated by Django 4.1 on 2022-10-01 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="YoutubeTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(blank=True, null=True)),
                ("sub_text", models.TextField(blank=True, null=True)),
                ("channel", models.TextField(blank=True, null=True)),
                ("img", models.TextField(blank=True, null=True)),
                ("url", models.TextField(blank=True, null=True)),
            ],
            options={"db_table": "youtube_test", "managed": False,},
        ),
    ]
