# Generated by Django 3.2.15 on 2022-10-05 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='youtubetest',
            table='youtube_test1',
        ),
    ]
